apiVersion: v1
kind: Service
metadata:
  name: oncoclear-api
  labels:
    app: oncoclear-api
spec:
  type: LoadBalancer
  selector:
    app: oncoclear-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
